import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Page from "./page";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
        flex flex-col min-h-screen
        bg-gradient-to-r from-zinc-900 via-black to-zinc-900
        ${nunito.className}
        `}
      >
        {children}
      </body>
    </html>
  );
}
